---
- name: create user and copy files into user home dir
  hosts: all 
  tasks:
    - name: create multiple users 
      user:
        name: "{{item.a}}"
        password: "{{item.b}}"
        home: "{{item.c}}"
      with_items:
        - {a: sravya,b: sravs,c: /tmp/sravya}
        - {a: chintu,b: chintu,c: /home/chintu}
    - name: copy files into users home dirs
      copy:
        src: "{{item.a}}"
        dest: "{{item.b}}"
        owner: "{{item.c}}"
        group: "{{item.d}}"
        mode: "{{item.e}}"
      with_items:
         - {a: /etc/passwd,b: /tmp/sravya,c: sravya,d: chintu,e: 751}
         - {a: /etc/group,b: /home/chintu,c: chintu,d: sravya,e: 574}

...
