---
- name: Install/Uninstall using loops
  hosts: all
  tasks:
    - name: Install/Uninstall of s/w's apps
      apt: 
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: tree,b: present,c: no}
        - {a: git,b: absent,c: no}
        - {a: maven,b: present,c: yes}

...
