---
- name: create users and create fils/dirs in the users home dir
  hosts: all
  tasks: 
    - name: create users
      user: 
        name: "{{a}}"
        password: "{{b}}"
        home: "{{c}}" 
    - name: create fils/dirs in user home dir
      file: 
        name: "{{d}}"
        state: "{{e}}"

...
