---
- name: configuring tomcat
  hosts: all
  tasks: 
    - name: Install tomcat10
      apt:
        name: tomcat10
        state: present
        update_cache: yes
    - name: Install tomcat10-admin
      apt: 
        name: tomcat10-admin
        state: present
    - name: copy tomcat-users.xml file
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat10
    - name: change port of tomcat from 8080 to 9090
      replace:
        regexp: 8080
        replace: 9090
        path: /etc/tomcat10/server.xml
    - name: restart tomcat10
      service:
        name: tomcat10
        state: restarted
    - name: pause module for 1 min
      pause:
        minutes: 1
    - name: check tomcat response on server11
      uri:
        url: http://172.31.19.9:9090
        status_code: 200
    - name: check tomcat response on server22
      uri:
        url: http://172.31.18.113:9090
        status_code: 200
