---
- name: create users on all servers
  hosts: all
  tasks:
     - name: user creation
       user:
          name: sravya
          password: sravya
          uid: 1111
          shell: /bin/bash
          comment: "A normal user"
          home: /tmp/sravya 


...

